language: ruby
rvm: "2.2"

before_install:
  - gem update --system
  - gem --version

install: bundle install

after_install:
  - jekyll --version

script: jekyll build --verbose --incremental && github-pages health-check

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
