language: ruby
rvm:
- 2.3

before_install:
  - gem update --system
  - gem --version

install: bundle install

script: jekyll build --verbose && github-pages health-check

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
