language: ruby
rvm: "2.6"

before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle --version

install: bundle install

after_install:
  - bundle exec jekyll --version

script:
  - bundle exec jekyll build --verbose --incremental
  - bundle exec github-pages health-check || true

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
