# Site settings
title: 'Eldhusid & +'
email: tolva@tuta.io
description: 'Le blog culinaire de Tolva.'
baseurl: ''
url: 'http://deild.github.io/'
# Social usernames/URLs
twitter_username: MhinTolva
github_username: deild
instagram_username: mihntolva
flickr_username: mhintolva

# Build settings
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown

timezone: Europe/Paris

# Site settings
title_description: 'Bonne lecture et dégustation.'
title_image: 'https://c1.staticflickr.com/9/8859/17896320759_6b73e37514_o.png'
github_repository: https://github.com/deild/deild.github.io
post_limit: 5

permalink: /:categories/:year/:month/:day/:title
exclude: [vendor, README.md]

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
